konveyor/editor-extensions

vscode/.vscode/launch.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/src/styles.css, vscode/webpack.config.ts
Enable webpack watch mode to allow npm run watch to work as expected rather than needing to npm run compile every time you make a change.
=> Enable webpack watch

vscode/.vscode/launch.json, vscode/package-lock.json, vscode/package.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/tsconfig.json, vscode/webpack.config.js, vscode/webpack.config.ts
- When 'npm run watch' is run you are now able to properly debug the ui code with sourcemaps enabled. 
- Adds missing dependencies. Fixes:
```
➜  vscode git:(main) npm run compile
> konveyor@0.0.1 compile
> webpack --mode production --config webpack.config.ts
[webpack-cli] Unable load '/home/ibolton/Development/editor-extensions/vscode/webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from '/home/ibolton/Development/editor-extensions/vscode'
[webpack-cli] Cannot find module 'sucrase/register/ts' from '/home/ibolton/Development/editor-extensions/vscode'
[webpack-cli] Cannot find module '@babel/register' from '/home/ibolton/Development/editor-extensions/vscode'
[webpack-cli] Cannot find module …
```
=> Add sourcemaps for development mode

vscode/package.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/src/VsCodeExtension.ts, vscode/src/commands.ts, vscode/src/extensionState.ts, vscode/src/webview/components/App.tsx, vscode/src/webviewContent.ts
- Add placeholder menu items for analyzing specific files from the explorer view 
- Add placeholder startAnalysis command 
- Create utility function for getting the webview content since it is being used in panel and sidebar webviews
- Create extension state to hold any new webview providers. Allows access to the state without having to change function signatures to pass in any new webviews to the registerCommand function as they are created.
=> :sparkles: Add extension state and analysis placeholders

.gitignore, analyzer/README.md
- Fixed broken link at `analyzer/README.md`
- Added items to`.vscode` 
Fixes : #42
=> :book: fixed broken link at README.md and added items in .gitignore

.husky/pre-commit, package.json, vscode/.husky/pre-commit
- Current husky version has a different way to install
- The `lint-staged` action should run at the repo root so all repos are linted/fixed by the pre-commit script
=> :seedling: Update husky to run across the repo

vscode/media/walkthroughs/override-analyzer.md, vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts
- Add kai-rpc server Path property which user can override
Fixes #62 #64
=> :sparkles: Start kai/rpc-server

.github/workflows/ci-repo.yml, .github/workflows/nightly-ci-repo.yaml, .github/workflows/release.yml
Avoid installing our git hooks when running CI in github actions since the `lint-staged` work doesn't matter in CI.
See https://typicode.github.io/husky/how-to.html#ci-server-and-docker
=> :seedling: Disable husky git hooks in github actions

vscode/package.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/src/commands.ts, vscode/src/data/index.ts, vscode/src/data/loadResults.ts, vscode/src/data/loadStaticResults.ts, vscode/src/data/storage.ts, vscode/src/data/virtualStorage.ts, vscode/src/diffView/copyCommands.ts, vscode/src/diffView/fileModel.ts, vscode/src/diffView/solutionCommands.ts, vscode/src/extension.ts, vscode/src/extensionState.ts, vscode/src/utilities/constants.ts, vscode/src/utilities/index.ts, vscode/src/utilities/typeGuards.ts
Key points:
1. make the data folder(.vscode/konveyor) the main permanent storage.
This replaces the current usages of vscode.workspaceState.
2. store analysis results and received solutions directly in the
extension state. Both values are frequently read from the command
layer. Retrieval from the DB adds unnecessary delay.
3. load initial data asynchronously on extension start
4. implement commands: applyAll,applyFile, revertAll, revertFile,
copyPath, copyDiff
5. create loadResultsFromDataFolder command ("Reload results" in the
command palette)for initial data load and development.
Resolves: https://github.com/konveyor/editor-extensions/issues/48
Resolves: https://github.com/konveyor/editor-extensions/issues/72
=> :sparkles: Load state from files and create apply/revert/copy commands

.github/CODEOWNERS
Created a team specifically for reviewing IDE related work. This PR makes them CODEOWNERS of this repository.
=> :ghost: use special kai-ide-reviewers as reviewers

package-lock.json, shared/package.json, vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/data/analyzerResults.ts, vscode/src/data/loadResults.ts, vscode/src/data/loadStaticResults.ts, vscode/src/data/storage.ts, vscode/src/data/virtualStorage.ts, vscode/src/extensionState.ts, vscode/src/test/analyzerResults.test.ts, vscode/src/utilities/typeGuards.ts, webview-ui/package.json, webview-ui/src/App.tsx, webview-ui/src/components/GuidedApproachWizard.tsx, webview-ui/src/components/ViolationIncidentsList.tsx
The `@shared/types` package does not actually exist. It was only working because there was a vestigial reference for it in the `package-lock.json` file from before the shared workspace package was renamed from `@shared/types` to `@editor-extensions/shared`. `@shared/types` was pointing to the shared workspace.
Fixes:
- Remove the `@shared/types` reference in the lock file
- Refactor all of the imports to pull from the current npm package name
=> :seedling: Refactor shared package imports

vscode/src/commands.ts
Previously, when you selected a file to override the default path, the path was saved and couldn't be reset. With this update:
- If you open the file selection dialog but don’t choose a file, the path will reset to undefined.
- When no path is set, the default binary from the /assets/bin folder will be used.
=> :bug:  Reset Path

vscode/package.json, vscode/src/commands.ts, vscode/src/data/readOnlyStorage.ts, vscode/src/diffView/register.ts, vscode/src/diffView/solutionCommands.ts, vscode/src/utilities/constants.ts
Changes:
1. add optional configuration property "diffEditorType". If set to
"merge" then open resolutions using merge editor. Otherwise use
the diff editor.
2. create text document content provider for serving read only virtual
files to be used as left side of the merge. Register the provider
under "konveyorReadOnly" scheme.
=> :sparkles: Support reviewing resolutions with merge editor

.gitignore, collect-assets.js, package-lock.json, package.json, scripts/collect-assets.js
Downloading kai analyzer & server
=> :seedling: initial collect-assets script

.github/workflows/release.yml
=> :seedling: Update release workflow with new npm targets

package-lock.json, package.json, scripts/_download.js, scripts/_util.js, scripts/collect-assets.js
Split the contents of `collect-assets.js` into two files. The base file has the release details.  The new `_download.js` file has the functions that do the download and extract work.
This split helps keep the `collect-assets.js` script as small as possible to make future configuration changes easier.
=> :seedling: Split `collect-assets.js` code, add `tar.gz` download

shared/src/types/index.ts, vscode/src/data/loadResults.ts, vscode/src/data/storage.ts, vscode/src/data/virtualStorage.ts, vscode/src/utilities/typeGuards.ts
Map solution response to internal format using only information from the provided diff.
Main advantages:
1. automatically map files to corresponding diffs - apply/discard operations are file based and require single-file diff
2. allows incremental update to support add/delete/rename
3. file paths in git diffs are relative to repository root which usually maps to VS Code workspace
Main disadvantage is increasing the dependency on the git diff format.
Reference-Url: https://github.com/konveyor/kai/issues/502
=> :sparkles: Retrieve the list of modified files from the diff

mocks/coolstore_fixEverywhere_javax_ejb_Stateless.json, mocks/coolstore_fix_catalog_source_javax_ejb_Stateless.json, package-lock.json, shared/src/types/index.ts, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/data/loadResults.ts, vscode/src/extension.ts, vscode/src/extensionState.ts, vscode/src/utilities/typeGuards.ts, vscode/src/webviewMessageHandler.ts, webview-ui/package.json, webview-ui/src/components/AnalysisPage.tsx, webview-ui/src/components/FileChanges.tsx, webview-ui/src/components/IncidentList.tsx, webview-ui/src/components/ProgressIndicator.tsx, webview-ui/src/components/ResolutionsPage.tsx, webview-ui/src/components/SolutionCard.tsx, webview-ui/src/components/ViolationCard.tsx, webview-ui/src/components/ViolationIncidentsList.tsx
Refactor and where necessary partially revert the code introduced in feature/kai branch.
Changes:
1. base the webview view/apply/discard actions on state property
localChanges which contains parsed and localized resolutions.
2. refactor async code in analyzer client
a) use promisfied versions of exec and setTimeout
b) create synchronous version of  canAnalyze
c) extract extension state mutations to dedicated fire*Change methods
d) introduce ServerState enum
3. save raw response (solutionData) and scope using loadSolution command
to better link those entities.
4. re-create Uri objects received in the message handler from webviews.
After crossing the iframe boundary only data props are preserved.
5. remove triggering checkServerStatus message from the webviews as the
new onDataChanged event …
=> :sparkles:  Reintroduce multi-file support

vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/diffView/solutionCommands.ts, vscode/src/utilities/configuration.ts, vscode/src/utilities/constants.ts, vscode/src/utilities/index.ts
This PR adds the kai configuration items to our extension's config **AND** attempts to standardize the way we get and update our configuration items.
=> :sparkles: Add kai configurables to extension config

shared/src/types/actions.ts, vscode/media/walkthroughs/start-analyzer.md, vscode/media/walkthroughs/start-server.md, vscode/package.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/data/loadResults.ts, vscode/src/extension.ts, vscode/src/webviewMessageHandler.ts, webview-ui/src/components/AnalysisPage.tsx, webview-ui/src/components/FileChanges.tsx, webview-ui/src/components/ServerStatusToggle/ServerStatusToggle.tsx, webview-ui/src/components/ServerStatusToggle/styles.css, webview-ui/src/components/ViolationActionsDropdown.tsx, webview-ui/src/components/ViolationIncidentsList.tsx, webview-ui/src/hooks/actions.ts
- Disable analysis and getSolution if server is not running
- Move server status and prevent blocking analysis sidebar when server is starting
- Fix webview ready message to follow "type" convention
- Change startAnalysis to runAnalysis across all files
https://github.com/user-attachments/assets/d68bb713-8fde-482a-94fa-f4cbc3860086
=> :sparkles: Add server status component

scripts/copy-dist.js, vscode/.vscodeignore
Since `vsce` was complaining about a missing `.vscodeignore`, that file has been cleaned up and included in the copy-dist file list.  The warning is gone, and nothing changes with respect to the packaged contents.
=> :seedling: Fix vsce packaging warning

.github/workflows/ci-repo.yml, .github/workflows/release.yml
All platform builds include the binaries for all platforms.  No need to upload more than one of those builds.
=> :seedling: upload only one artifact

vscode/src/client/analyzerClient.ts
The kai rpc server needs the `GENAI_KEY` envvar to be set so it can start up.  A valid key is _not_ needed to be able to run analysis.
Update the kai rpc server env function to insert the dummy value but let it be overridden by the value available in vscode's the actual envvars.
=> :seedling: Include dummy `GENAI_KEY` in rpc server env

eslint.config.mjs, package-lock.json, shared/src/types/types.ts, vscode/package.json, vscode/src/analysis/__tests__/data.ts, vscode/src/analysis/__tests__/mergeRuleSets.test.ts, vscode/src/analysis/index.ts, vscode/src/analysis/mergeRuleSets.ts, vscode/src/analysis/runAnalysis.ts, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/data/analyzerResults.ts, vscode/src/data/loadResults.ts, vscode/src/data/storage.ts, vscode/src/diffView/register.ts, vscode/src/extension.ts, vscode/src/extensionState.ts, vscode/src/utilities/configuration.ts, vscode/src/utilities/constants.ts, webview-ui/src/components/AnalysisPage.tsx, webview-ui/src/components/ViolationIncidentsList.tsx
1. register onDidSaveTextDocument() listener to track save operations
inside editors and ensure proper clean-up
2. explicitly trigger partial analysis for files modified via apply
actions
3. send chosen files inside included_paths parameter
4. save received responses with prefix "partial_analaysis" - this prevents
multiple subsequent requests from overwriting last full analysis
5. save the result of merging the response with current state to files with
prefix "merged_analysis" - this allows debugging and loading last state
on IDE start
6. both partial_analysis and merged_analysis files are remove on the next
full analysis
Test changes:
1. remove unused chai lib - the syntax used for assertions triggers
eslint errors
2. use assertion from  "expect" lib known from Jest
3. create test:local …
=> :sparkles: Trigger partial analysis after save

vscode/src/client/analyzerClient.ts
=> :bug: Remove hardcoded dummy key

webview-ui/src/App.tsx, webview-ui/src/components/AnalysisPage/AnalysisPage.tsx, webview-ui/src/components/AnalysisPage/styles.css, webview-ui/src/components/ViolationsCount/ViolationsCount.tsx, webview-ui/src/components/ViolationsCount/styles.css
=> :sparkles: Add counts and styling for incident / issues 

shared/src/types/types.ts, vscode/package.json, vscode/src/KonveyorGUIWebviewViewProvider.ts, vscode/src/commands.ts, vscode/src/extension.ts, vscode/src/extensionState.ts, vscode/src/issueView/expandCommands.ts, vscode/src/issueView/index.ts, vscode/src/issueView/issueModel.ts, vscode/src/issueView/register.ts, vscode/src/issueView/transformation.ts, webview-ui/src/App.tsx, webview-ui/src/hooks/useExtensionState.ts, webview-ui/src/utils/vscode.ts
Layout:
1. group incidents by message (top level) and file (2nd level)
2. within message group the files are sorted based on the entire path
3. within file group the incidents are sorted based on line number
Actions:
1. top bar
1. open Analysis webview 
2. expand all nodes 
2. context:
1. open details in Analysis webview (currently just opens the webview) 
2. expand all child nodes
3. one-click expand for nodes with only one child 
4. open Analysis webview when extension is loaded (first time the perspective is accessed)
Refactorings:
1. move Analysis web view to the editor section (similar to Resolution webview)
2. disable full screen toggling for Analysis webview
3. embed initial state data in the HTML to ensure that first message won't be missed
Reference-Url: …
=> :sparkles: Add issue tree view

vscode/src/client/analyzerClient.ts
=> :bug: make analysis runs cancellable

vscode/media/walkthroughs/configure-get-Solution-params.md, vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/utilities/configuration.ts
https://github.com/user-attachments/assets/b8932454-7255-4c32-88b5-f02a2c581150
=> :sparkles: Add configuration for getSolution params

vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/utilities/configuration.ts
- Toml values overwrite configured settings. Removing these values for now. 
- Add in defaults for providerArgs
- Allow demoMode to be set from settings.json
=> :sparkles: Remove default toml arguments and use settings.json

package-lock.json, package.json, vscode/src/client/analyzerClient.ts
The `kai-rpc-server` processes generate some working directories that are created in the process's given working directory. Set the process's current working directory to a path under the workspace's `.vscode/` directory.  This will ensure that if multiple vscode windows are open, the konveyor runtime binaries will not clash with each other.
The process will run with a cwd of:
`{{workspace_root}}/.vscode/konveyor/kai-runtime`
=> :sparkles: Set cwd for `kai-rpc-server` to a `.vscode/` path

scripts/_download.js, scripts/collect-assets.js
- Use release v0.0.3
- Adjust `collect-assets.js` to use the "new" asset names
- Use case insensitive asset name matching between release
assets and the configurations
- Add linux and windows arm64 builds
=> :seedling: Use kai binaries from release v0.0.3

vscode/src/client/analyzerClient.ts
Resolves: #160
Pending https://github.com/konveyor/kai/pull/526, this change is needed so the kai-rpc-server starts.  The initialize call should still override any model configurations in the toml file.
Once the kai change to remove `config.toml` is merged, the TODOs added by this change will need to be resolved.
=> :bug: Add back default config.toml values

package-lock.json, vscode/README.md, vscode/package.json
=> :seedling: update vscode extension readme

vscode/src/client/analyzerClient.ts
Update initialize parameters to align with https://github.com/konveyor/kai/pull/526. Please feel free to commit to this PR.
=> :ghost: Update analyzerClient.ts

shared/src/types/types.ts, vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/client/types.ts, vscode/src/utilities/configuration.ts
Based on changes to the kai runtime configurations in https://github.com/konveyor/kai/pull/526, update the CLI arguments and initialize request object to match.
Summary of changes:
- Reorder the config field definitions
- Use enum values in config definitions where available
- Config keys related to analyzer configuration still remain but cannot be passed along to the analyzer, see [kai issue 550](https://github.com/konveyor/kai/issues/550)
- Aligned CLI arguments and initialize request payload types to the updated Kai configuration keys
- Dropped config.toml handling since that file is no longer in use
Prerequisite for: #184
=> :seedling: Update config definitions, base configs and initialize call

vscode/src/client/analyzerClient.ts
- The server's cwd is tracked as a Uri but passed to spawn as the actual file system path to make sure it runs there
- Remove `kaiRuntimeDir` since it isn't needed anymore
=> :ghost: refactor analyzerClient server cwd

extra-types/array-filter-Boolean.d.ts, extra-types/index.d.ts, extra-types/package.json, package-lock.json, package.json, vscode/src/client/analyzerClient.ts
Use a new workspace project `extra-types` that installs to `@types/extra-types` as a way to make `Array.filter(boolean)` have the correct typing across all of the ts projects in the repo.  Typescript "makes visible" all typing from packages installed under `node_modules/@types`.  Put our override there and no extra configurations needed.  Magic.
=> :seedling: Fix typing on `Array.filter(Boolean)` for the project

shared/src/types/types.ts, vscode/src/client/analyzerClient.ts, vscode/src/extension.ts, webview-ui/src/components/AnalysisPage/AnalysisPage.tsx, webview-ui/src/components/ResolutionsPage.tsx, webview-ui/src/components/ServerStatusToggle/ServerStatusToggle.tsx, webview-ui/src/hooks/useExtensionState.ts
Resolves https://github.com/konveyor/editor-extensions/issues/187
- Update fireStateChange -> fireServerStateChange for clarity
- Add additional server state for initialization. This is purely to handle the unhandled started but not initialized case that can arise for now. 
TODO: Handle readyToInitialize case. Comment out the fire state event until this is ready to be handled.
=> :bug: Add initialization state tracking to prevent spawning duplicate 

vscode/media/walkthroughs/override-analyzer.md, vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/utilities/configuration.ts, vscode/src/utilities/fileUtils.ts
Resolves #224 
Resolves #218 
- This PR allows for ease of binary override by using the custom methods available in the walkthrough or command palette. Previously the override was silently failing when trying to write paths to the user settings. Changed the scope to allow workspace / global settings. Also, enabled selection of all file extension types and included an executable check post selection. Improved error message & success messaging when path operations succeed or fail.
=> :bug: Allow override of binaries in workspace & global settings.

package.json, scripts/collect-assets.js, scripts/copy-dist.js, shared/package.json, vscode/package.json, webview-ui/package.json
Prepare release 0.0.5
- Bump `collect-assets.js` to use kai 0.0.5
- Refine the `copy-dist.js` file globs given updated kai asset contents
- Bump `package.json` versions to 0.0.5
=> :seedling: Release 0.0.5

package-lock.json, scripts/copy-dist.js
- fix dist copy glob for kai binaries
- updating `package-lock.json` file after version bumps
=> :seedling: release 0.0.5-1

package-lock.json, package.json, scripts/collect-assets.js, shared/package.json, vscode/package.json, webview-ui/package.json
=> :seedling: Release 0.0.6

vscode/package.json
Resolves https://github.com/konveyor/editor-extensions/issues/185
When a user closes VS Code with open tabs that reference resources from our custom file system (konveyorMemFs or konveyorReadOnly), those tabs fail to load on the next startup. This is because our extension does not activate automatically on VS Code startup or when restoring those resources. Instead, the extension only activates when the user interacts with the sidebar, leading to errors such as:
"The editor could not be opened due to an unexpected error: Unable to resolve resource konveyorReadOnly:/path/to/resource"
Fix:
We added activationEvents to package.json to ensure the extension activates automatically when resources using our custom schemes (konveyorMemFs and konveyorReadOnly) are accessed. This ensures that the …
=> :bug: Ensure konveyor file system resources are resolved during session restore

docs/roadmap/stories/01-configuration_and_runtime_support.md
=> :book: Update 01-configuration_and_runtime_support.md

vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/client/types.ts, vscode/src/utilities/configuration.ts
This adds the ability for users to generate new cached data and also adds an option to generate the LLM traces.
=> :sparkles: add config options for cache_dir and trace

webview-ui/src/components/ResolutionsPage.tsx
Resolves: #255
Resolution details should only show the "All resolutions have been applied" message when a resolution has been received.
=> :bug: Fix errant resolution details message on second resolution request

vscode/src/commands.ts
=> :bug: use word characters for source+target selection

vscode/src/commands.ts
Additionally, this removes the final "screen" where the user can manually modify the labelSelector as it caused confusion in what was finally configured. Intelligent users can just modify their settings.json directly.
Fixes #274
=> :seedling: display target quickpick first

vscode/src/client/analyzerClient.ts
Logging of the rpc server init request got dropped in recent changes.  Adding the logging back to the output channel for easier debugging.
=> :ghost: Add logging of the rpc server init request

vscode/package.json, vscode/src/client/analyzerClient.ts, vscode/src/client/tracer.ts, vscode/src/utilities/configuration.ts
To make it easier to work between the jsonrpc server and the extension client, add the ability to trace the messaging to an output channel.
Details:
- The output channel's name is of the form: `${basename(kai-rpc-server)} message trace`
- The trace output channel is created when the server is first started, and is independent from the `Konveyor-Analyzer` channel
- Tracing is controlled by the configuration key `konveyor.logging.traceMessageConnection`. It is `false` by default.
Note: Supports #315
=> :seedling: Add ability to trace the jsonrpc MessageConnection

vscode/package.json
The `diff` view requires use of proposed APIs. Swap the default to the one that will both work without special measures and will let the extension be
published to the extension markplace.
Ref: #222
Note: This change does not remove the proposed api use warnings vscode shows at startup.
=> :sparkles: Change default diff editor to `merge`

vscode/src/extension.ts
Incident file path information changed to use Uri values.  Since the `workspaceRoot` being handed to the webviews was fsPath based, the full Uris were being rendered.  Pass the workspaceRoot as a Uri string and get the `relativeDirname()` function working properly again.
Resolves: #252
=> :bug: Fix Analysis and Resolution file paths relative to workspaceRoot

vscode/package.json, vscode/resources/sample-provider-settings.yaml, vscode/src/commands.ts, vscode/src/extension.ts, vscode/src/utilities/fileUtils.ts
Two changes:
- Remove the sample key text to shorten any time to fail on solution requests if a user doesn't put the keys in the right place
- Add a command to allow a user to backup their existing `provider-setting.yaml` file and reset it back to the extension default/sample file
This is a partial fix for #327.
=> :sparkles: Remove key text from `sample-provider-settings.yaml`, add a command to reset

.github/workflows/ci-repo.yml, .github/workflows/release.yml, package-lock.json, package.json, scripts/_download.js, scripts/_github.js, scripts/collect-assets.js
Refactor the `collect-assets` scripts so every call to the GitHub API can be authorized with the GITHUB_TOKEN envvar.  This will help prevent rate limiting encountered by CI and Release actions.
Summary:
- Setup `GITHUB_TOKEN` in actions as needed
- Use `@octokit/core` for GitHub API access as it can default auth and it has lots of nice typing and rich information if errors are encountered
- GitHub fetch functions are now all in `_github.js`
- try/catch blocks moved as high as possible, any `await function` call that fails will be passed up
=> :seedling: collect-assets refactored to use GitHub API with auth

vscode/src/client/analyzerClient.ts
No incidents were detected in this file after reanalysis. It seems the issue has been resolved or is no longer relevant. Rewording notification for clarity.
=> :bug: Rewording notfication for better user experience

package-lock.json, package.json, scripts/collect-assets.js, shared/package.json, vscode/package.json, webview-ui/package.json
=> :seedling: release 0.0.8

vscode/src/extension.ts
If the jsonrpc server is running when the extension is deactivated, which is usually caused by exiting vscode, stop the server.
Resolves: #272
=> :bug: Properly stop the jsonrpc server on extension deactivation

vscode/src/extension.ts, webview-ui/src/components/IncidentTable/IncidentTable.tsx, webview-ui/src/utils/__tests__/incidentRelativeDir.test.ts, webview-ui/src/utils/incident.ts
=> :bug: handle incident uri on windows

shared/src/types/types.ts, vscode/src/data/loadResults.ts, webview-ui/src/components/ViolationCard.tsx, webview-ui/src/components/ViolationIncidentsList.tsx
* Make the list of incidents sort ascending/descending based on the grouping (issues | files)
* Add new toggle for the sort
* Swap severity filter for category filter that actually exist on incidents.
Fixes #358 
Fixes #369
=> :sparkles: make the incident list sortable

package-lock.json, shared/src/types/types.ts, vscode/src/client/analyzerClient.ts, vscode/src/extension.ts, webview-ui/package.json, webview-ui/src/components/ResolutionsPage/ChatMessage.tsx, webview-ui/src/components/ResolutionsPage/ChatMessageComponent.tsx, webview-ui/src/components/ResolutionsPage/ResolutionsPage.tsx, webview-ui/src/hooks/useExtensionState.ts, webview-ui/src/index.css, webview-ui/src/index.tsx
Resolves: #352
Supports: https://github.com/konveyor/kai/pull/652
Built on: #374
Add `MarkdownChatMessage` and `JsonChatMessage` rendering to the resolution webview.
Markdown is configured to support:
- Basic Markdown [1]
- GitHub Flavored Markdown [2], [3]
- HTML embedded in Markdown [4]
- Syntax highlighting [5] in code \`\`\` blocks similar to what GitHub supports
- Final string renders are sanitized so only "valid" HTML will make it to the page while invalid HTML is escaped and will show as normal text [6]
Json messages are formatted, wrapped in a Markdown code block, and syntax highlighting is used to render it as a message.
[1]: https://remarkjs.github.io/react-markdown
[2]: https://github.github.com/gfm
[3]: https://github.com/remarkjs/react-markdown
[4]: …
=> :sparkles: Add support for markdown and json solution progress messages

webview-ui/src/components/ResolutionsPage/ChatMessageComponent.tsx, webview-ui/src/components/ResolutionsPage/chatMessageComponent.css
Signed-off-by: Ian Bolton <ibolton@redhat.com>
=> :bug: Fix wrapping on markdown messages

vscode/package.json, vscode/src/commands.ts, vscode/src/data/loadResults.ts, vscode/src/data/loadStaticResults.ts, vscode/src/data/virtualStorage.ts
Resolves https://github.com/konveyor/editor-extensions/issues/336
- Remove the default solution load behavior on startup
- Remove the reload last solution button from the diff view
- Update to display the diff view when you hard load a solution from a file using the "Load Results from File" command.
=> :bug: At extension startup, reload analysis result but do not reload solutions

webview-ui/src/components/GetSolutionDropdown.tsx, webview-ui/src/components/IncidentTable/IncidentTable.tsx, webview-ui/src/components/ViolationIncidentsList.tsx, webview-ui/src/utils/__tests__/incidentPath.test.ts, webview-ui/src/utils/__tests__/incidentRelativeDir.test.ts, webview-ui/src/utils/incident.ts
This PR fixes problems with rendering the incident table(s).
* When isReadOnly, we shouldn't be rendering the solution dropdown
* When isReadOnly, we don't actually need to full rendered path because it gets cluttered
* We need to handle windows paths with care, not just for relative paths but when computing the filename from the incident.uri
* Some other minor tweaks to the look and feel of the table and solution dropdown
Fixes #398
Fixes #400
=> :bug: respect isReadOnly for solution dropdown

webview-ui/src/components/ResolutionsPage/ResolutionsPage.tsx
This is related to https://github.com/konveyor/kai/issues/697
We sometimes see same error messages in responses from different attempts of fixing an issue. This PR merges same messages into one line and appends the no of times the error was seen to that line.
=> :bug: deduplicate encountered errors in chat view

webview-ui/src/components/GetSolutionDropdown.tsx
Resolves https://github.com/konveyor/editor-extensions/issues/397
When using the plain button variant, we don't need to use "sm" size. This was originally added to create space between button backgrounds in table view.
=> :bug: Remove sm size to restore button alignment

vscode/package.json, vscode/src/utilities/configuration.ts
The following keys and related functions have been removed:
- konveyor.kai.genAiKey
- konveyor.kai.providerArgs
- konveyor.kai.providerName
These keys are no longer needed after adoption of `provider-settings.yaml`.
=> :bug: Remove unused configuration keys

vscode/src/analysis/runAnalysis.ts, vscode/src/extension.ts
Resolves: #344
Only send a document that has been saved to partial analysis if the document was actually changed.  Just hooking the `onDidSaveTextDocument()` event is not enough to determine if a change was actually made to a document being saved. Track document changes by file uri and check that list on save.
=> :bug: Only run partial analysis if a file was changed

vscode/media/walkthroughs/open-analysis-panel.md, vscode/package.json
- Addresses the comment from 
[@Pranav](https://redhat-internal.slack.com/team/UJVF3G38W) on https://github.com/konveyor/editor-extensions/issues/425 - the walkthrough button isn’t stateful so we were able to start the server but there were no notifications or button state on the walkthrough that let us know that the server was starting/initializing. You could click it a bunch of times and kick off several instances of the server. The fix in PR 433 just ushers the user to the analysis page and encourages the user to start the server from there.
=> :bug: Redirect user to analysis page at the end of the konveyor walkthrough

vscode/src/client/analyzerClient.ts, vscode/src/client/types.ts
Depends on https://github.com/konveyor/kai/pull/731
=> :bug: pass label selector via initialize()

.gitignore, package-lock.json, package.json, scripts/_download.js, scripts/_github.js, scripts/_unpack.js, scripts/_util.js, scripts/collect-assets.js
Resolves: #234
Resolves: #334
Update the collect-assets script such that assets can be sourced from GitHub release assess or from a GitHub workflow's artifacts.  Download of assets and artifacts is separated from unpacking of the assets.
When complete, the full set of downloaded assets that the editor-extensions can use will be located under `{project_root}/downloaded_assets`.
Downloaded files will have the ETag stored in a sidecar file.  This allows future runs to skip the download step if the url's data has not been changed.
Note: File globs are used during unpacking to allow extracting only a portion of an archive that is
relevant to the desired file set.
=> :seedling: Update collect-assets scripts

scripts/copy-dist.js
The jdtls bundle was going to the wrong location,
change the destination to the correct folder.
=> :bug: Fix copy-dist to put the jdtls bundle in the right place

.github/workflows/ci-repo.yml, .github/workflows/release.yml
On the `ci-repo.yml` action:
- pull assets from the Kai build workflow artifacts (the "latest" build)
- Note: If the head commit to the configured branch does not yet have a successful run of the build workflow, the collect-assets script should fail and fail the CI run
On the `release.yml` action:
- explicitly pull assets from the default configured Kai release
- update the workflows to mirror how `ci-repo.yml` builds the vsix
- write a release summary to the step output to see the info without opening the logs
- add a dry-run option to be able to test everything up to but not including posting the release
The source of all of the assets will be listed in the workflow run log.
=> :seedling: Adjust collect-asset sources on workflow actions

scripts/_download.js, scripts/_unpack.js, scripts/_util.js, scripts/collect-assets.js
Update the `collect-assets.js` script to use the sources release of the `konveyor/ruleset` repo as the source of the ruleset files. A single release of the ruleset repo is targeted.
Once this is merged, another PR will swap out the repo assets with the downloaded assets.
Follows: #453
=> :seedling: Collect rulesets directly from GitHub release

shared/src/types/types.ts, vscode/src/analysis/backoffManager.ts, vscode/src/analysis/batchedAnalysisTrigger.ts, vscode/src/analysis/runAnalysis.ts, vscode/src/client/analyzerClient.ts, vscode/src/client/types.ts, vscode/src/extension.ts, webview-ui/src/context/ExtensionStateContext.tsx
Fixes #472 
Introduces hot rerun of analysis in that analysis is run whenever - 
1. A file is saved (immediately)
2. A file is modified (after notifying file changes to the backend with a backoff)
- File changes are communicated to the backend, the backend is supposed to handle in-memory changes
Makes sure server is not overwhelmed at any point using backoffs but we may have to tweak the numbers as we test this more. So far its working well.
Needs https://github.com/konveyor/kai/pull/764
=> :sparkles: Feature/hot rerun of analysis

vscode/src/commands.ts, vscode/src/utilities/fileUtils.ts
=> :bug: make build files reload workspace configuration

.github/workflows/ci-repo.yml
- Remove the nightly-ci-repo.yml since I added a schedule directly to this workflow
- Updated the schedule to match the old nightly ci schedule
- Generate an asset name with the time (HHMM) as part of it so it's more unique and prevents conflicts
- Having a unique asset name causes the cleanup to break so do our own cleanup using gh.
=> :bug: Stop upload failures caused by duplicate names

webview-ui/src/components/ProfileManager/ProfileEditorForm.tsx, webview-ui/src/components/ProfileManager/ProfileList.tsx
- The active profile alert now includes a message stating that changes are saved automatically and no action is needed. This should help new users understand that they don't need to click "Make Active" to save their profile, as it's already active and saved by default.
-Also, added helper text for form fields and a label in header to indicate that changes auto-save.
Resolves https://github.com/konveyor/editor-extensions/issues/552
=> :sparkles: Manage profiles UX improvements

vscode/src/KonveyorGUIWebviewViewProvider.ts, webview-ui/src/context/ExtensionStateContext.tsx, webview-ui/src/index.css
In DevSpaces, there's often a race condition where React components mount before the extension fully initializes the webview data. 
There is also a CDN pf font that is unreachable in prod mode. This is now overridden by local PF fonts.
=> :bug: Fix type errors in dev spaces
