.github/workflows/ci-repo.yml
Fixing the version retrieval command
=> :bug: fix release

.github/workflows/ci-repo.yml
Fixing missing release artifacts.
example release - https://github.com/savitharaghunathan/editor-extensions/releases/tag/v0.0.1-dev%2B20241007
=> :bug: fix missing release artifacts

.github/workflows/ci-repo.yml
Sample run - https://github.com/savitharaghunathan/editor-extensions/actions/runs/11259070682/job/31307358613
https://github.com/savitharaghunathan/editor-extensions/releases/tag/v0.0.1-dev%2B20241009
This PR wraps up the last issue I saw with the initial automated release.
=> :bug: update the release conditional

mocks/coolstore_fixEverywhere_javax_ejb_Stateless.json, shared/src/types/index.ts, vscode/.vscodeignore, vscode/package.json, vscode/src/commands.ts, vscode/src/data/loadResults.ts, vscode/src/data/loadStaticResults.ts, vscode/src/data/storage.ts, vscode/src/data/typeGuards.ts, vscode/tsconfig.json
Changes:
1. add konveyor.loadSolution command used by existing command konveyor.loadStaticResults
2. store loaded analysis results and received solution inside ".vscode/konveyor" folder
a) last 5 files are stored for each type 
b) file name is unique - with human readable sufix (datetime)
4. change ECMA level to "ES2021" for libs to get String.replaceAll()
5. introduce Change interface with props:
a) "original" - relative file path before the change, may be empty if file was created in this change 
b) "modified" - relative file path after the change, may be empty if file was deleted in this change 
c) "diff" - diff in unified format - tested with git diffs
=> :sparkles: Load solutions from file

webview-ui/src/components/AnalysisPage.tsx
Add additional styling for analysis page
=> :sparkles: Analysis page styling

shared/src/types/actions.ts, vscode/src/webviewMessageHandler.ts, webview-ui/src/components/AnalysisPage/AnalysisPage.tsx, webview-ui/src/hooks/actions.ts
Resolves: #134
Wire the stop button to the stop server command already available via the command pallet.
=> :bug: Enable issues view server stop button

vscode/src/client/analyzerClient.ts, vscode/src/utilities/configuration.ts
- Prevent default args passed to incompatible models when user is setting a custom provider
=> :bug: Replace all default args if any provider args set

vscode/src/issueView/__tests__/transformations.test.ts, vscode/src/issueView/transformation.ts
=> :bug: Accept incidents without line number

vscode/src/extension.ts
Resolves https://github.com/konveyor/editor-extensions/issues/144
=> :bug: Fix error message when no workspace selected

webview-ui/src/components/ViolationIncidentsList.tsx
=> :bug: Align truncate with full screen expectations

vscode/src/data/analyzerResults.ts
Resolves: https://github.com/konveyor/editor-extensions/issues/177
=> :bug: Replace code snippet with rule name in the issue marker

shared/src/types/types.ts, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/webviewMessageHandler.ts, webview-ui/src/components/AnalysisPage/AnalysisPage.tsx, webview-ui/src/components/ResolutionsPage.tsx, webview-ui/src/hooks/actions.ts
Reference-Url: https://github.com/konveyor/editor-extensions/issues/171
=> :seedling: Refactor getSolution command to accept a list of incidents

vscode/src/client/analyzerClient.ts
=> :bug: Add a race condition when initialize request results in exit code

vscode/package.json
=> :bug: 0 max_iterations is invalid

webview-ui/src/components/ResolutionsPage.tsx
=> :bug: No all resolutions applied message when fetching new solution

vscode/src/client/analyzerClient.ts
=> :bug: fail visibly on server start

vscode/src/utilities/configuration.ts
This is a follow-up to #331 because I messed up and forgot to commit this change 😢 .
=> :bug: handle null max effort correctly

webview-ui/src/components/IncidentTable/IncidentTable.tsx
=> :bug: when no line number provided, say so

package-lock.json, webview-ui/.mocharc.json, webview-ui/package.json, webview-ui/src/__tests__/_.test.ts, webview-ui/src/__tests__/useViolations.test.ts
Add basic unit testing to the webview-ui package:
- Add a basic "do tests run?" test
- Setup the mocha runner so react components and hooks can be tested
- Add a basic set of tests for the `useViolations()` hook
=> :seedling: Add basic unit tests to webview-ui package

package-lock.json, package.json, scripts/collect-assets.js, shared/package.json, vscode/package.json, webview-ui/package.json
Package versions and collect-assets to version 0.0.10
=> :seedling: release 0.0.10

vscode/resources/sample-provider-settings.yaml
=> :book: Update sample-provider-settings.yaml with Ollama example

package-lock.json, package.json, scripts/collect-assets.js, shared/package.json, vscode/package.json, webview-ui/package.json
Package versions to 0.0.12 and collect-assets to release v0.0.12
=> :seedling: release 0.0.12

vscode/src/client/analyzerClient.ts
Resolves: #251
If analyze or getSolution is called, and the server is not running, do nothing and report it to the output channel.  This allows some actions to become no-ops if the kai jsonrpc server is not running.
The `serverState` changes have been further cleaned up to allow better state checking in the various action functions.
Previously the checks were not robust enough and used error messages to report the issue.  Error messages here are misleading at best.
=> :bug: Do rpc server actions only if the server is ready

webview-ui/src/components/IncidentTable/IncidentTable.tsx, webview-ui/src/utils/incident.ts
=> :bug: simplify issue rendering

vscode/src/client/analyzerClient.ts
=> :bug: load the results even when no rulesets

vscode/src/commands.ts, vscode/src/configureSourcesTargetsQuickPick.ts
Resolves https://github.com/konveyor/editor-extensions/issues/428
=> :bug: Save source/target onSelectionChange

package-lock.json, package.json, shared/package.json, vscode/package.json, webview-ui/package.json
Package versions to `0.1.0-pre.2`
collect-assets to release `v0.1.0-pre.2`
=> :seedling: release 0.1.0-pre.2

scripts/collect-assets.js
Missed this change on the original PR.
=> :seedling: release 0.1.0-pre.2 (including the update for collect-assets.js)

package-lock.json, package.json, scripts/collect-assets.js, shared/package.json, vscode/package.json, webview-ui/package.json
Package versions to `0.1.0`
Collect assets from Kai release `v0.1.0`
=> :seedling: release 0.1.0

shared/src/types/types.ts, webview-ui/src/components/ResolutionsPage/ChatCard/ChatCard.tsx, webview-ui/src/components/ResolutionsPage/ChatCard/chatCard.css, webview-ui/src/components/ResolutionsPage/ResolutionsPage.tsx, webview-ui/src/components/ResolutionsPage/resolutionsPage.css
Resolves https://github.com/konveyor/editor-extensions/issues/431
=> :bug: Fix initial user messages timestamp unwanted change

README.md, extra-types/array-filter-Boolean.d.ts
Update to include:
- collect-asset step for development and workflow/latest downloads
- how to build the vsix
- current project structure details
- current project build details
=> :book: Update README.md

package-lock.json, shared/src/types/actions.ts, shared/src/types/types.ts, vscode/package.json, vscode/src/ViolationCodeActionProvider.ts, vscode/src/commands.ts, vscode/src/data/analyzerResults.ts, vscode/src/data/loadResults.ts, vscode/src/extension.ts, vscode/src/test/analyzerResults.test.ts, vscode/src/utilities/configuration.ts, vscode/src/webviewMessageHandler.ts, webview-ui/src/components/GetSolutionDropdown.tsx, webview-ui/src/hooks/actions.ts
This makes it so we have a functional code action provider that allows us to either Ask Kai or Ask Continue with Konveyor Context.
Fixes #452
=> :sparkles: Implement functional CodeActionProvider with Continue

package-lock.json, package.json, shared/src/types/types.ts, vscode/package.json, vscode/src/ViolationCodeActionProvider.ts, vscode/src/commands.ts, vscode/src/extension.ts, vscode/src/utilities/configuration.ts, webview-ui/src/components/GetSolutionDropdown.tsx, webview-ui/src/components/ResolutionsPage/ResolutionsPage.tsx, webview-ui/src/context/ExtensionStateContext.tsx
=> :sparkles: talk to LLM provider(s) directly for RAG solution

webview-ui/src/components/ProfileManager/ProfileList.tsx, webview-ui/src/components/ProfileManager/ProfileManagerPage.tsx
=> :sparkles: Duplicate profile functionality

.gitignore, package-lock.json, package.json, scripts/copy-dist.js, shared/src/types/types.ts, vscode/package.json, vscode/src/ViolationCodeActionProvider.ts, vscode/src/analysis/backoffManager.ts, vscode/src/analysis/batchedAnalysisTrigger.ts, vscode/src/analysis/runAnalysis.ts, vscode/src/client/analyzerClient.ts, vscode/src/client/types.ts, vscode/src/commands.ts, vscode/src/extension.ts, vscode/src/utilities/configuration.ts, webview-ui/src/components/GetSolutionDropdown.tsx, webview-ui/src/components/ResolutionsPage/ResolutionsPage.tsx, webview-ui/src/context/ExtensionStateContext.tsx
- Talk to the LLM provider directly for RAG solution
- Use java extension to provide java language server. Now the editor extension mediates the communication between analyzer and java language services.
- Hot rerun analysis with queueing
=> :sparkles: do kai things in ide directly

webview-ui/src/components/ProfileManager/CreatableMultiSelectField.tsx, webview-ui/src/components/ProfileManager/ProfileEditorForm.tsx
Resolves https://github.com/konveyor/editor-extensions/issues/500
Resolves https://github.com/konveyor/editor-extensions/issues/493
- Searchable dropdown with full keyboard support for navigation and selection
- Adds creatable targets and sources to the profile form
=> :sparkles: Add createbleMultiSelectField component for managing src/tgt values

package-lock.json, package.json, shared/src/types/types.ts, vscode/src/client/analyzerClient.ts, vscode/src/commands.ts, vscode/src/data/loadResults.ts
=> :seedling: support ollama and track active profile

scripts/copy-dist.js
=> :bug: update contributes.javaExtensions

vscode/resources/sample-provider-settings.yaml, vscode/src/client/modelProvider.ts, vscode/src/client/types.ts, vscode/src/commands.ts
=> :bug: fix model provider configuration

tests/e2e/tests/analyze_coolstore.test.ts
**Description:**
This PR updates `analyze_coolstore.test.ts` to reflect recent application changes.  It addresses issues described in #630.
**Key updates include:**
- **UI Locator Fix:** Adjusted the fixLocator to target `'button[aria-label="Accept all changes"]' `in resolution view tests.
- **Profile Name Generation:** Adapted tests to the externalized random string generation for profile names (aligning with PR #626), ensuring unique test profiles per run.
These changes are crucial for maintaining the workflow of the E2E tests.
=> :seedling:: Update coolstore analysis E2E tests for UI & profile changes
